# Generated by Django 2.1.4 on 2018-12-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryArea',
            fields=[
                ('country_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_area_name', models.CharField(max_length=100, unique=True)),
                ('m49_code', models.SmallIntegerField()),
                ('iso_alpha3_code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'UNSD M49 Country or Area',
                'verbose_name_plural': 'UNSD M49 Countries or Areas',
                'db_table': 'country_area',
                'ordering': ['country_area_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTargetIndicator',
            fields=[
                ('country_target_indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('countrycode', models.CharField(blank=True, max_length=255, null=True)),
                ('seriescode', models.CharField(blank=True, max_length=255, null=True)),
                ('indicator_value', models.CharField(blank=True, db_column='Indicator_Value', max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'UNMDG Country Indicator',
                'verbose_name_plural': 'UNMDG Country Target Indicators',
                'db_table': 'country_target_indicator',
                'ordering': ['indicator_value'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevStatus',
            fields=[
                ('dev_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_status_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'UNSD M49 Country or Area Development Status',
                'verbose_name_plural': 'UNSD M49 Country or Area Development Statuses',
                'db_table': 'dev_status',
                'ordering': ['dev_status_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'UNMDG Goal',
                'verbose_name_plural': 'UNMDG Goals',
                'db_table': 'goal',
                'ordering': ['goal_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indicator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorValueType',
            fields=[
                ('indicator_value_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_value_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'UNMDG Indicator Value Name',
                'verbose_name_plural': 'UNMDG Indicator Value Names',
                'db_table': 'indicator_value_type',
                'ordering': ['indicator_value_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateRegion',
            fields=[
                ('intermediate_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('intermediate_region_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'UNSD M49 Intermediate Region',
                'verbose_name_plural': 'UNSD M49 Intermediate Regions',
                'db_table': 'intermediate_region',
                'ordering': ['intermediate_region_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=50, unique=True)),
                ('unsd_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'UNSD Planet Name',
                'verbose_name_plural': 'UNSD Planet Names',
                'db_table': 'planet',
                'ordering': ['planet_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'UNSD M49 Region',
                'verbose_name_plural': 'UNSD M49 Regions',
                'db_table': 'region',
                'ordering': ['region_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('sub_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_region_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'UNSD M49 Subregion',
                'verbose_name_plural': 'UNSD M49 Subregions',
                'db_table': 'sub_region',
                'ordering': ['sub_region_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'UNMDG Target',
                'verbose_name_plural': 'UNMDG Targets',
                'db_table': 'target',
                'ordering': ['target_name'],
                'managed': False,
            },
        ),
    ]
